[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.98"
application     = { path = "../application"     }
pretty_env_logger = "0.5.0"
toml = "0.8.22"
