services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 83893
      POSTGRES_DB: ppo
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ppo"]
      interval: 5s
      timeout: 5s
      retries: 5

  rombet:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:83893@postgres:5432/ppo
      LC_DATABASE_URL: ":memory:"
    volumes:
      - ./test-results:/app/test-results
      - ./allure-report:/app/allure-report
      - ./allure-history:/app/allure-history
    depends_on:
      postgres:
        condition: service_healthy
    command: 
      - sh
      - -c
      - |
        ./make_report.sh
    networks:
      - app-network

networks:
  app-network:
    driver: bridge