[package]
name = "application"
version.workspace = true
edition.workspace = true

[dependencies]
domain          = { path = "../domain"          }

anyhow = "1.0.97"
serde = {version = "1.0.219", default-features = false, features = ["std", "derive"]}
toml = "0.8.20"
rand = "0.9.0"