[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.97"
uuid = {version="1.16.0", features = ["v7", "serde"]}
serde = {version = "1.0.219", default-features = false, features = ["std", "derive"]}
rand = "0.9.0"
